### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by alick** [vanshady/quanti-fi-tools#6]
SSPL is quite controversial. Mongodb has released SSPL v2, but it was not approved by OSI. It has been rejected by Debian, Red Hat, etc.

**Comment by vanshady** [comment]
I agree with you, but I plan to potentially support more features and more platforms, such as chrome extensions and mobile apps), as a service, which I'm not sure that I'll get enough help from the community, so the intention here is to support personal use or educational use but not commercial use.

**Comment by alick** [comment]
I understand your concern, but it essentially makes this work non-open
source... Please consider well received alternatives, such as GNU AGPL, or
even dual licensing...
